In [ ]:
import os
import numpy as np
import pandas as pd

# Set working directory to project root
os.chdir("/Users/mac/Desktop/valorant-ml-project")

df_overview = pd.read_csv("data/raw/detailed_matches_overview.csv")
df_maps     = pd.read_csv("data/raw/detailed_matches_maps.csv")
df_matches  = pd.read_csv("data/raw/matches.csv")
df_player     = pd.read_csv("data/raw/detailed_matches_player_stats.csv")
df_agent = pd.read_csv("data/raw/performance_data.csv")

In [53]:
df_overview.head()
df_overview.info()
#df_overview.shape
#df_overview.columns

<class 'pandas.DataFrame'>
RangeIndex: 34 entries, 0 to 33
Data columns (total 10 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   match_id       34 non-null     int64
 1   match_title    34 non-null     str
 2   event          34 non-null     str
 3   date           34 non-null     str
 4   format         34 non-null     str
 5   teams          34 non-null     str
 6   score          34 non-null     str
 7   maps_played    34 non-null     int64
 8   patch          34 non-null     str
 9   pick_ban_info  34 non-null     str
dtypes: int64(2), str(8)
memory usage: 2.8 KB

In [51]:
df_maps.head()
#df_maps.info()
#df_maps.shape
#df_maps.columns

   match_id map_name  map_order   score     winner duration      picked_by
0    542195     Bind          1  13 - 9  Paper Rex    48:56  Xi Lai Gaming
1    542195   Sunset          2  13 - 5  Paper Rex    39:04      Paper Rex
2    542196  Corrode          1  6 - 13  Sentinels    41:17      Sentinels
3    542196   Sunset          2  13 - 4     GIANTX    38:15         GIANTX
4    542196    Haven          3  13 - 9     GIANTX    51:34        Decider

In [ ]:
df_matches.head()
#df_matches.info()
#df_matches.shape
#df_matches.columns

,date,match_id,time,team1,score1,team2,score2,score,winner,status,week,stage
0,"Fri, September 12, 2025",542195,6:30 PM,Paper Rex,2,Xi Lai Gaming,0,2-0,Paper Rex,Completed,Opening (A),Group Stage
1,"Fri, September 12, 2025",542196,8:55 PM,GIANTX,2,Sentinels,1,2-1,GIANTX,Completed,Opening (A),Group Stage
2,"Sat, September 13, 2025",542207,6:30 PM,NRG,2,EDward Gaming,0,2-0,NRG,Completed,Opening (C),Group Stage
3,"Sat, September 13, 2025",542205,9:25 PM,Team Liquid,0,DRX,2,0-2,DRX,Completed,Opening (C),Group Stage
4,"Sun, September 14, 2025",542212,6:30 PM,Dragon Ranger Gaming,0,T1,2,0-2,T1,Completed,Opening (D),Group Stage

In [ ]:
df_matches.head()